## Exercise 1: Hamming distance

Write a `hamming()` function that calculates the Hamming distance between two words when they have the same length, and returns −1 otherwise.

- Indication:

    The Hamming distance between two vectors is simply the sum of corresponding elements that differ between the vectors.

    - For example, suppose we have the following two vectors:
    ```python
    x = [1, 2, 3, 4]
    y = [1, 2, 5, 7]
    ```
    - The Hamming distance between the two vectors would be 2, since this is the total number of corresponding elements that have different values.


### 

In [2]:
def harming_distance(x,y):
    a=0
    for i in range(len(x)):
        if x[i]!=y[i]:
            a=a+1
    return(a)
x=[1,2,3,4]
y=[1,2,5,7]

print(harming_distance(x,y))

            

2


## Exercise 2: Syracuse sequence

We define the Syracuse sequence ($u_n$) by $u_0$ $\in$ $\mathbb{N}$ and

$$
u_n + 1 = \left\{
    \begin{array}{ll}
        \frac{u_n}{2} \mbox{ if $u_n$ is even} \\
        3u_{n+1} \mbox{ if $u_n$ is odd} 
    \end{array}
\right.
$$

1. Write a `syracuse()` function which takes as input two integers $u_0$ and $n$ and returns $u_n$.
2. Check that we always end up with cycle $4,2,1,4,2,1,\dots$, for $0 \leq u_0 \leq 20$.
3. Given u_0 $\in$ $\mathbb{N}$ denote $h$ the smallest of the integers $n$ such that $u_n = 1$ (we assume that such $h$ exists).
    - Write a function `height()` which takes as input $u_0$ and calculates $h$.
4. Calculate the couples ($u_0$, height($u_0$)) for $u_0 \leq 100$.

In [20]:
def syracuse(n,indice):
    for i in range(indice):
        if n%2==0:
            n=n/2
        else:
            n=3*n+1
    return(n)
print(syracuse(2,5))

            
        
        
        
        
    
    

4.0


## Exercise 3: 

We consider the application $\sigma = \mathbb{N^*} \to \mathbb{N^*}$ which associates with each integer $n$ the sum of the cubes of the digits of its writing in base 10. 
- For example, if $n = 123$ then $\sigma(n) = 1^3 + 2^3 + 3^3 = 36$.

1. Write a `sigma()` function that takes as input a non-zero integer $n$ and returns the sum of cubes of its digits in base 10.

2. Find all integers $n \leq 1000$ such that $\sigma(n) = n$.

3. Given $a \in \mathbb{N^*}$, we are interested in the sequence ($u_n(a)$) defined by $u_0(a) = a$ and $u_{n+1}(a) = \sigma(u_n(a))$.

4. For several values of a, display the first 20 terms of the sequence ($u_n(a)$).

5. Show using the computer that for all $1 \leq a \leq 9999$ which is a multiple of 3 we have $u_{13}(a) = 153$.

In [51]:
#1st question
def sigma(n):
    num=str(n)
    l=[]
    for a in num:
        l.append(int(a)**3)
    p=sum(l)
    return(p)

    
print(sigma(123))

#2nd question
for i in range(1,1001):
    if sigma(i)==i:
        print('nombre verifiant 0(n)=n sont:',i)
#3rd question

def calculating(i):
    import random
    a=random.randint(1,100)
    p=a
    for i in range(i):
        x=sigma(p)
        print(x)
        p=x
    
#5th question
for a in range(1,10000):
    if a%3==0:
        calculating(13)
        

    

    

36
nombre verifiant 0(n)=n sont: 1
nombre verifiant 0(n)=n sont: 153
nombre verifiant 0(n)=n sont: 370
nombre verifiant 0(n)=n sont: 371
nombre verifiant 0(n)=n sont: 407
28
520
133
55
250
133
55
250
133
55
250
133
55
945
918
1242
81
513
153
153
153
153
153
153
153
153
344
155
251
134
92
737
713
371
371
371
371
371
371
72
351
153
153
153
153
153
153
153
153
153
153
153
730
370
370
370
370
370
370
370
370
370
370
370
370
520
133
55
250
133
55
250
133
55
250
133
55
250
341
92
737
713
371
371
371
371
371
371
371
371
371
737
713
371
371
371
371
371
371
371
371
371
371
371
793
1099
1459
919
1459
919
1459
919
1459
919
1459
919
1459
432
99
1458
702
351
153
153
153
153
153
153
153
153
16
217
352
160
217
352
160
217
352
160
217
352
160
737
713
371
371
371
371
371
371
371
371
371
371
371
468
792
1080
513
153
153
153
153
153
153
153
153
153
343
118
514
190
730
370
370
370
370
370
370
370
370
64
280
520
133
55
250
133
55
250
133
55
250
133
280
520
133
55
250
133
55
250
133
55
250
133
55
730
370
37

133
55
250
133
55
250
1024
73
370
370
370
370
370
370
370
370
370
370
370
855
762
567
684
792
1080
513
153
153
153
153
153
153
793
1099
1459
919
1459
919
1459
919
1459
919
1459
919
1459
1
1
1
1
1
1
1
1
1
1
1
1
1
72
351
153
153
153
153
153
153
153
153
153
153
153
520
133
55
250
133
55
250
133
55
250
133
55
250
1241
74
407
407
407
407
407
407
407
407
407
407
407
737
713
371
371
371
371
371
371
371
371
371
371
371
54
189
1242
81
513
153
153
153
153
153
153
153
153
64
280
520
133
55
250
133
55
250
133
55
250
133
520
133
55
250
133
55
250
133
55
250
133
55
250
737
713
371
371
371
371
371
371
371
371
371
371
371
520
133
55
250
133
55
250
133
55
250
133
55
250
189
1242
81
513
153
153
153
153
153
153
153
153
153
280
520
133
55
250
133
55
250
133
55
250
133
55
2
8
512
134
92
737
713
371
371
371
371
371
371
217
352
160
217
352
160
217
352
160
217
352
160
217
35
152
134
92
737
713
371
371
371
371
371
371
371
35
152
134
92
737
713
371
371
371
371
371
371
371
8
512
134
92
737
713
371
371
371
371
37

## Exercise 4: 

We call magic square of order n, any square matrix $M$ of order $n$ whose elements are the integers from 1 to $n^2$ arranged so that their sums on each line, on each column and on the two diagonals are equal. The common value of these sums is called the magic constant of $M$, and we have in fact $M = \frac{n(n^2+1)}{2}$.

1. Write a `permutation()` function that takes an array $T$ consisting of $n$ integers and decides if $T$ is a permutation of {1, 2, $\dots$ , n}.
    - We will first check if all the elements of $T$ are in {1, 2,$\dots$, n}.
    - Then we will check that no element of $T$ is repeated.
    
2. Write a function `magic_square()` which makes it possible to decide if a square matrix $M$ is a magic square.
    - We will first start by checking if the array M.flatten() is a permutation of {1, 2, $\dots$ , $n^2$}.
    - We will then use slicing to check if the sums of rows, columns and the two diagonals are the same.
    
3. Using the `magic_square()` function find the magic squares of order 2.

In [3]:
# first question
def permutation(a):
    n=len(a)
    if n==0:
        return False
    for i in a:
        if i<1 or i>n:
            return False
        if len(set(a))!=n:
            return False
        return true

#second question
def mqgicsquqre(a):
    n=len(a)
    if n==0:
        return false
    for i in matrix:
        if len(i)!=n:
            return False
    sommedudiag1=0
    sommedudiag2=0
    for i in range(n):
        sommedudiag1+=a[i][i]
        sommedudiag2+=a[i][n-i-1]
    if sommedudiag1 !=sommedudiag2:
        return False
    for i in range(n):
        sumofrows=0
        sumofcolums=0
        for j in range(n):
            sumofrows+=a[i][j]
            sumofcolums+=a[j][i]
        if sumofrows!=sommedudiag1 or sumofcolums!=sommedudiag1:
            return False
        return True

## Exercise 5:

1. Randomly generate a matrix $M$ of real numbers. Then calculate the tables of means, variances and standard deviations of the lines of $M$.

2. Doing a search, find numpy functions and methods to do the same job as in question 1. without using loops.

In [4]:
import numpy as np

def matrix_function(M):
    n_rows = len(M)
    n_cols = len(M[0])
    dictionnaire = []
    for i in range(n_rows):
        row = M[i]
        mean = np.mean(row)
        variance = np.var(row)
        std_dev = np.std(row)
        dictionnaire.append({'mean': mean, 'variance': variance, 'std_dev': std_dev})
    return dictionnaire
M=np.random.rand(3,4)
print(M)
print(matrix_function(M))



[[0.80194592 0.55450005 0.1573186  0.67832305]
 [0.71974014 0.33210748 0.06845005 0.17973488]
 [0.56142326 0.08027914 0.30526904 0.26683886]]
[{'mean': 0.5480219039406623, 'variance': 0.05853670705658577, 'std_dev': 0.24194360304952428}, {'mean': 0.325008136998325, 'variance': 0.0606975306665741, 'std_dev': 0.2463686884865325}, {'mean': 0.3034525752483884, 'variance': 0.02942477933497379, 'std_dev': 0.17153652478400566}]


## Execise 6:

A square matrix $M$ of order $n$ is said to be stochastic if all its coefficients are in [0,1] and the sum of the coefficients of each row of $M$ is equal to 1.

1. Write a test function `stoch()` which verifies if a square matrix $M$ is stochastic.
2. Write a function `stoch(n)` which allows to randomly generate a stochastic matrix of order $n$.
3. Write a `sequence()` function which takes as input a stochastic matrix $M$ of order $n$ and a vector $V$ of size $n$ as well as an integer $d$ and displays the vectors

$$
V, M.V, M^2.V, \dots , M^d.V
$$

- To calculate the product $M.V$ we use the `dot()` function by simply writing ```np.dot(M,V)```.

4. For fixed $n$, for example 4, randomly generate a stochastic matrix $M$ of order $n$ and a vector of size $n$. Then test the function `sequence()` on $M$ and $V$ with several values of $d$. Repeat this experiment several times and draw a conclusion.

In [6]:
# first question
import numpy as np
def stoch(M):
    nbr_rows,nbr_colums=np.shape(M)
    if nbr_rows!=nbr_colums:
        return False
    for i in range(nbr_rows):
        if sum(M[i])>1:
            return false
    return true
# second question
def stoch(n):
    M=np.random.rand(n,n)
    for i in range(n):
        M[i]=M[i]|M[i].sum()
    return M

    
    